# Generated by Django 4.2.7 on 2023-11-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0001_initial'),
        ('donates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donates',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram_users.telegramusers'),
        ),
    ]
