# Generated by Django 4.2.7 on 2023-11-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='heroes/')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('marksman', 'Marksman'), ('mage', 'Mage'), ('fighter', 'Fighter'), ('tank', 'Tank'), ('support', 'Support')], max_length=10)),
                ('salary', models.IntegerField()),
                ('health', models.IntegerField()),
                ('restore_health', models.IntegerField()),
                ('steal_health', models.IntegerField()),
                ('stealing_health_protection', models.IntegerField()),
                ('magical_attack', models.IntegerField()),
                ('physical_attack', models.IntegerField()),
                ('magical_protection', models.IntegerField()),
                ('physical_protection', models.IntegerField()),
                ('control', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='UserHeroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heroes.heroes')),
            ],
        ),
    ]
