# Generated by Django 4.2.7 on 2023-11-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equipments/')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('salary', models.IntegerField()),
                ('health', models.IntegerField()),
                ('restore_health', models.IntegerField()),
                ('steal_health', models.IntegerField()),
                ('stealing_health_protection', models.IntegerField()),
                ('magical_attack', models.IntegerField()),
                ('physical_attack', models.IntegerField()),
                ('magical_protection', models.IntegerField()),
                ('physical_protection', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='UserEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipments.equipments')),
            ],
        ),
    ]
