# Generated by Django 4.2.7 on 2023-11-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('war_user', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userequipments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='war_user.waruser'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='users',
            field=models.ManyToManyField(related_name='equipments_related', through='equipments.UserEquipments', to='war_user.waruser'),
        ),
    ]
