# Generated by Django 4.2.7 on 2023-11-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('war_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('is_started', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'War',
                'verbose_name_plural': 'Wars',
            },
        ),
        migrations.CreateModel(
            name='WarUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='war_user.waruser')),
                ('war_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wars.wars')),
            ],
        ),
        migrations.AddField(
            model_name='wars',
            name='users',
            field=models.ManyToManyField(related_name='wars_related', through='wars.WarUsers', to='war_user.waruser'),
        ),
    ]
