# Generated by Django 4.2.7 on 2023-11-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0001_initial'),
        ('equipments', '0001_initial'),
        ('heroes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=0)),
                ('health', models.IntegerField()),
                ('restore_health', models.IntegerField()),
                ('steal_health', models.IntegerField()),
                ('stealing_health_protection', models.IntegerField()),
                ('magical_attack', models.IntegerField()),
                ('physical_attack', models.IntegerField()),
                ('magical_protection', models.IntegerField()),
                ('physical_protection', models.IntegerField()),
                ('control', models.BooleanField()),
                ('control_protection', models.BooleanField()),
                ('line', models.IntegerField()),
                ('is_attack', models.BooleanField(default=False)),
                ('is_dead', models.BooleanField(default=False)),
                ('is_control', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipments', models.ManyToManyField(related_name='war_users_related', through='equipments.UserEquipments', to='equipments.equipments')),
                ('hero_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heroes.heroes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram_users.telegramusers')),
            ],
            options={
                'verbose_name': 'War-User',
                'verbose_name_plural': 'War-Users',
            },
        ),
    ]
